apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia-readiness-probe
spec:
  replicas: 3
  selector:
    app: kubia-rp
  template:
    metadata:
      labels:
        app: kubia-rp
    spec:
      containers:
      - name: kubia
        image: vinayaksingoriya/kubia
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          exec:
            command:
            - ls
            - /var/ready
