## This method is deprecates in the current version.

apiVersion: v1
kind: Pod
metadata:
  name: gitrepo-volume-pod
spec:
  containers:
  - image: alpine
    name: web-server
    command: ["sh", "-c", "apk add --no-cache git && sleep infinity"]
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP
  volumes:
  - name: html
    gitRepo:
      repository: https://github.com/VinayakSingoriya/kubia-website-example.git
      revision: master
      directory: .